select * FROM
(select
--*
'OMC8' OMC
,RSSI.PERIOD_START_TIME SDATETIME
,CMRBTS.CO_OBJECT_INSTANCE MRBTSID
,CLNBTS.CO_OBJECT_INSTANCE LNBTSID
,CLNBTS.CO_OBJECT_INSTANCE || '-' || CLNCEL.CO_OBJECT_INSTANCE ENB_CELL
,RSSI.RSSI_PUSCH_AVG - SINR.SINR_PUSCH_AVG 干扰值
from
NOKLTE_PS_LPQUL_MNC_RAW RSSI inner join ctp_common_objects CLNCEL on RSSI.LNCEL_ID = CLNCEL.Co_Gid
INNER JOIN CTP_COMMON_OBJECTS CLNBTS ON RSSI.LNBTS_ID = CLNBTS.CO_GID
INNER JOIN CTP_COMMON_OBJECTS CMRBTS ON RSSI.MRBTS_ID = CMRBTS.CO_GID
INNER JOIN NOKLTE_PS_LPQUL_MNC_RAW SINR ON SINR.LNCEL_ID = RSSI.LNCEL_ID
WHERE
RSSI.PERIOD_START_TIME = SINR.PERIOD_START_TIME
AND RSSI.PERIOD_START_TIME >= TO_DATE(&STIME,'YYYYMMDDHH24MI')
AND RSSI.PERIOD_START_TIME < TO_DATE(&ETIME,'YYYYMMDDHH24MI')

UNION ALL

select
--*
'OMC6' OMC
,RSSI.PERIOD_START_TIME SDATETIME
,CMRBTS.CO_OBJECT_INSTANCE MRBTSID
,CLNBTS.CO_OBJECT_INSTANCE LNBTSID
,CLNBTS.CO_OBJECT_INSTANCE || '-' || CLNCEL.CO_OBJECT_INSTANCE ENB_CELL
,RSSI.RSSI_PUSCH_AVG - SINR.SINR_PUSCH_AVG 干扰值
from
NOKLTE_PS_LPQUL_MNC_RAW@OMC6 RSSI inner join ctp_common_objects@OMC6 CLNCEL on RSSI.LNCEL_ID = CLNCEL.Co_Gid
INNER JOIN CTP_COMMON_OBJECTS@OMC6 CLNBTS ON RSSI.LNBTS_ID = CLNBTS.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC6 CMRBTS ON RSSI.MRBTS_ID = CMRBTS.CO_GID
INNER JOIN NOKLTE_PS_LPQUL_MNC_RAW@OMC6 SINR ON SINR.LNCEL_ID = RSSI.LNCEL_ID
WHERE
RSSI.PERIOD_START_TIME = SINR.PERIOD_START_TIME
AND RSSI.PERIOD_START_TIME >= TO_DATE(&STIME,'YYYYMMDDHH24MI')
AND RSSI.PERIOD_START_TIME < TO_DATE(&ETIME,'YYYYMMDDHH24MI')

UNION ALL

select
--*
'OMC7' OMC
,RSSI.PERIOD_START_TIME SDATETIME
,CMRBTS.CO_OBJECT_INSTANCE MRBTSID
,CLNBTS.CO_OBJECT_INSTANCE LNBTSID
,CLNBTS.CO_OBJECT_INSTANCE || '-' || CLNCEL.CO_OBJECT_INSTANCE ENB_CELL
,RSSI.RSSI_PUSCH_AVG - SINR.SINR_PUSCH_AVG 干扰值
from
NOKLTE_PS_LPQUL_MNC_RAW@OMC7 RSSI inner join ctp_common_objects@OMC7 CLNCEL on RSSI.LNCEL_ID = CLNCEL.Co_Gid
INNER JOIN CTP_COMMON_OBJECTS@OMC7 CLNBTS ON RSSI.LNBTS_ID = CLNBTS.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC7 CMRBTS ON RSSI.MRBTS_ID = CMRBTS.CO_GID
INNER JOIN NOKLTE_PS_LPQUL_MNC_RAW@OMC7 SINR ON SINR.LNCEL_ID = RSSI.LNCEL_ID
WHERE
RSSI.PERIOD_START_TIME = SINR.PERIOD_START_TIME
AND RSSI.PERIOD_START_TIME >= TO_DATE(&STIME,'YYYYMMDDHH24MI')
AND RSSI.PERIOD_START_TIME < TO_DATE(&ETIME,'YYYYMMDDHH24MI')

UNION ALL

select
--*
'OMC9' OMC
,RSSI.PERIOD_START_TIME SDATETIME
,CMRBTS.CO_OBJECT_INSTANCE MRBTSID
,CLNBTS.CO_OBJECT_INSTANCE LNBTSID
,CLNBTS.CO_OBJECT_INSTANCE || '-' || CLNCEL.CO_OBJECT_INSTANCE ENB_CELL
,RSSI.RSSI_PUSCH_AVG - SINR.SINR_PUSCH_AVG 干扰值
from
NOKLTE_PS_LPQUL_MNC_RAW@OMC9 RSSI inner join ctp_common_objects@OMC9 CLNCEL on RSSI.LNCEL_ID = CLNCEL.Co_Gid
INNER JOIN CTP_COMMON_OBJECTS@OMC9 CLNBTS ON RSSI.LNBTS_ID = CLNBTS.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC9 CMRBTS ON RSSI.MRBTS_ID = CMRBTS.CO_GID
INNER JOIN NOKLTE_PS_LPQUL_MNC_RAW@OMC9 SINR ON SINR.LNCEL_ID = RSSI.LNCEL_ID
WHERE
RSSI.PERIOD_START_TIME = SINR.PERIOD_START_TIME
AND RSSI.PERIOD_START_TIME >= TO_DATE(&STIME,'YYYYMMDDHH24MI')
AND RSSI.PERIOD_START_TIME < TO_DATE(&ETIME,'YYYYMMDDHH24MI')

UNION ALL

select
--*
'OMC3' OMC
,RSSI.PERIOD_START_TIME SDATETIME
,CMRBTS.CO_OBJECT_INSTANCE MRBTSID
,CLNBTS.CO_OBJECT_INSTANCE LNBTSID
,CLNBTS.CO_OBJECT_INSTANCE || '-' || CLNCEL.CO_OBJECT_INSTANCE ENB_CELL
,RSSI.RSSI_PUSCH_AVG - SINR.SINR_PUSCH_AVG 干扰值
from
NOKLTE_PS_LPQUL_MNC_RAW@OMC3 RSSI inner join ctp_common_objects@OMC3 CLNCEL on RSSI.LNCEL_ID = CLNCEL.Co_Gid
INNER JOIN CTP_COMMON_OBJECTS@OMC3 CLNBTS ON RSSI.LNBTS_ID = CLNBTS.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC3 CMRBTS ON RSSI.MRBTS_ID = CMRBTS.CO_GID
INNER JOIN NOKLTE_PS_LPQUL_MNC_RAW@OMC3 SINR ON SINR.LNCEL_ID = RSSI.LNCEL_ID
WHERE
RSSI.PERIOD_START_TIME = SINR.PERIOD_START_TIME
AND RSSI.PERIOD_START_TIME >= TO_DATE(&STIME,'YYYYMMDDHH24MI')
AND RSSI.PERIOD_START_TIME < TO_DATE(&ETIME,'YYYYMMDDHH24MI')

UNION ALL

select
--*
'OMC5' OMC
,RSSI.PERIOD_START_TIME SDATETIME
,CMRBTS.CO_OBJECT_INSTANCE MRBTSID
,CLNBTS.CO_OBJECT_INSTANCE LNBTSID
,CLNBTS.CO_OBJECT_INSTANCE || '-' || CLNCEL.CO_OBJECT_INSTANCE ENB_CELL
,RSSI.RSSI_PUSCH_AVG - SINR.SINR_PUSCH_AVG 干扰值
from
NOKLTE_PS_LPQUL_MNC_RAW@OMC5 RSSI inner join ctp_common_objects@OMC5 CLNCEL on RSSI.LNCEL_ID = CLNCEL.Co_Gid
INNER JOIN CTP_COMMON_OBJECTS@OMC5 CLNBTS ON RSSI.LNBTS_ID = CLNBTS.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC5 CMRBTS ON RSSI.MRBTS_ID = CMRBTS.CO_GID
INNER JOIN NOKLTE_PS_LPQUL_MNC_RAW@OMC5 SINR ON SINR.LNCEL_ID = RSSI.LNCEL_ID
WHERE
RSSI.PERIOD_START_TIME = SINR.PERIOD_START_TIME
AND RSSI.PERIOD_START_TIME >= TO_DATE(&STIME,'YYYYMMDDHH24MI')
AND RSSI.PERIOD_START_TIME < TO_DATE(&ETIME,'YYYYMMDDHH24MI')
)
--WHERE
--MRBTSID IN ('')
--LNBTSID IN ('')
