SELECT
--*
'OMC6' OMC
,OO.Co_Name||'-'||O.Co_Object_Instance BSCBCF
,BCF.BCF_BCPIA_19 BCFIP
FROM
C_BSC_BCF@OMC6 BCF INNER JOIN CTP_COMMON_OBJECTS@OMC6 O ON BCF.OBJ_GID = O.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC6 OO ON O.CO_PARENT_GID = OO.CO_GID
WHERE
BCF.CONF_ID = 1

UNION ALL

SELECT
--*
'OMC7' OMC
,OO.Co_Name||'-'||O.Co_Object_Instance BSCBCF
,BCF.BCF_BCPIA_19 BCFIP
FROM
C_BSC_BCF@OMC7 BCF INNER JOIN CTP_COMMON_OBJECTS@OMC7 O ON BCF.OBJ_GID = O.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC7 OO ON O.CO_PARENT_GID = OO.CO_GID
WHERE
BCF.CONF_ID = 1

UNION ALL

SELECT
--*
'OMC9' OMC
,OO.Co_Name||'-'||O.Co_Object_Instance BSCBCF
,BCF.BCF_BCPIA_19 BCFIP
FROM
C_BSC_BCF@OMC9 BCF INNER JOIN CTP_COMMON_OBJECTS@OMC9 O ON BCF.OBJ_GID = O.CO_GID
INNER JOIN CTP_COMMON_OBJECTS@OMC9 OO ON O.CO_PARENT_GID = OO.CO_GID
WHERE
BCF.CONF_ID = 1
