SELECT
--*
'OMC6' OMC
,OOOO.CO_OBJECT_INSTANCE MRBTSID
,ALD.ALD_R_CNF_DN
,DECODE(ALD.ALD_R_OPERATIONAL_ST,1,'ENABLE',0,'DISABLE') ALDSTATE
,ALD.ALD_R_SERIAL_NBR
FROM
C_SRER_ALD_R@OMC6 ALD
, CTP_COMMON_OBJECTS@OMC6 O
, CTP_COMMON_OBJECTS@OMC6 OO
, CTP_COMMON_OBJECTS@OMC6 OOO
, CTP_COMMON_OBJECTS@OMC6 OOOO
WHERE
ALD.OBJ_GID = O.CO_GID
AND ALD.CONF_ID = 1
AND O.CO_PARENT_GID = OO.CO_GID
AND OO.CO_PARENT_GID = OOO.CO_GID
AND OOO.CO_PARENT_GID = OOOO.CO_GID


UNION ALL

SELECT
--*
'OMC7' OMC
,OOOO.CO_OBJECT_INSTANCE MRBTSID
,ALD.ALD_R_CNF_DN
,DECODE(ALD.ALD_R_OPERATIONAL_ST,1,'ENABLE',0,'DISABLE') ALDSTATE
,ALD.ALD_R_SERIAL_NBR
FROM
C_SRER_ALD_R@OMC7 ALD
, CTP_COMMON_OBJECTS@OMC7 O
, CTP_COMMON_OBJECTS@OMC7 OO
, CTP_COMMON_OBJECTS@OMC7 OOO
, CTP_COMMON_OBJECTS@OMC7 OOOO
WHERE
ALD.OBJ_GID = O.CO_GID
AND ALD.CONF_ID = 1
AND O.CO_PARENT_GID = OO.CO_GID
AND OO.CO_PARENT_GID = OOO.CO_GID
AND OOO.CO_PARENT_GID = OOOO.CO_GID

UNION ALL

SELECT
--*
'OMC9' OMC
,OOOO.CO_OBJECT_INSTANCE MRBTSID
,ALD.ALD_R_CNF_DN
,DECODE(ALD.ALD_R_OPERATIONAL_ST,1,'ENABLE',0,'DISABLE') ALDSTATE
,ALD.ALD_R_SERIAL_NBR
FROM
C_SRER_ALD_R@OMC9 ALD
, CTP_COMMON_OBJECTS@OMC9 O
, CTP_COMMON_OBJECTS@OMC9 OO
, CTP_COMMON_OBJECTS@OMC9 OOO
, CTP_COMMON_OBJECTS@OMC9 OOOO
WHERE
ALD.OBJ_GID = O.CO_GID
AND ALD.CONF_ID = 1
AND O.CO_PARENT_GID = OO.CO_GID
AND OO.CO_PARENT_GID = OOO.CO_GID
AND OOO.CO_PARENT_GID = OOOO.CO_GID
